## Deliverable 3. Create a Travel Itinerary Map.

In [55]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import gmaps.datasets
import numpy as np

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [56]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
file = "../Vacation_Search/WeatherPy_vacation.csv"

vacation_df = pd.read_csv(file)
vacation_df.head()

City_ID           City Country  Max Temp        City_Descr    Lat     Lng  \
0        2  Cockburn Town      TC     87.80  scattered clouds  21.46  -71.14   
1        5        Tazmalt      DZ     77.00   overcast clouds  36.39    4.40   
2        6          Diffa      NE     83.62         clear sky  13.32   12.61   
3       10        Labuhan      ID     75.60  scattered clouds  -6.88  112.21   
4       19     Eydhafushi      MV     82.22         clear sky   5.10   73.07   

           Hotel Name  
0  Osprey Beach Hotel  
1       Hôtel Numédia  
2        ProDAF/Diffa  
3        bador sepret  
4        Soneva Fushi

In [13]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>City Name</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Weather Description</dt><dd>{City_Descr}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
city_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]


In [15]:
# 4a. Add a marker layer for each city to the map.
max_temp = vacation_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=city_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# 4b. Display the figure
fig


Figure(layout=FigureLayout(height='420px'))

In [81]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_df.loc[vacation_df["City"]=="Edson"]
vacation_end = vacation_df.loc[vacation_df["City"]=="Edson"]
vacation_stop1 = vacation_df.loc[vacation_df["City"]=="La Ronge"]
vacation_stop2 = vacation_df.loc[vacation_df["City"]=="Flin Flon"] 
vacation_stop3 = vacation_df.loc[vacation_df["City"]=="Neepawa"] 

In [82]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
#coords = vacation_df[["Lat", "Lng"]] == (vacation_df["City"]=="Cabra") & (vacation_df["City"]=="Marseille") & (vacation_df["City"]=="Capoterra") & (vacation_df["City"]=="Syracuse")

start = vacation_start[["Lat", "Lng"]]
starta = start.to_numpy()

end =  vacation_end[["Lat", "Lng"]]
enda = end.to_numpy()

stop1 = vacation_stop1[["Lat", "Lng"]]
stop1a = stop1.to_numpy()

stop2 = vacation_stop2[["Lat", "Lng"]]
stop2a = stop2.to_numpy()


stop3 = vacation_stop3[["Lat", "Lng"]]
stop3a = stop3.to_numpy()

print(starta)
print(enda)
print(stop1a)
print(stop2a)
print(stop3a)

[[  53.58 -116.44]]
[[  53.58 -116.44]]
[[  55.1  -105.28]]
[[  54.77 -101.86]]
[[ 50.23 -99.47]]


In [83]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".

# coordinate pairs
Edson = 53.58, -116.44
End_Edson = 53.58, -116.44
La_Ronge = 55.1, -105.28
Nipawin = 54.77, -101.86
Neepawa = 50.23, -99.47

fig = gmaps.figure()
trip = gmaps.directions_layer(Edson, End_Edson, waypoints=[La_Ronge, Nipawin, Neepawa], travel_mode="DRIVING")
fig.add_layer(trip)
fig


Figure(layout=FigureLayout(height='420px'))

In [84]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start, vacation_stop1, vacation_stop2, vacation_stop3, vacation_end],ignore_index=True)
itinerary_df


City_ID       City Country  Max Temp        City_Descr    Lat     Lng  \
0      387      Edson      CA      80.6         clear sky  53.58 -116.44   
1      303   La Ronge      CA      77.0        few clouds  55.10 -105.28   
2      248  Flin Flon      CA      80.6  scattered clouds  54.77 -101.86   
3       70    Neepawa      CA      86.0        few clouds  50.23  -99.47   
4      387      Edson      CA      80.6         clear sky  53.58 -116.44   

                           Hotel Name  
0  Holiday Inn Express & Suites Edson  
1               Northland Motor Hotel  
2              Victoria Inn Flin Flon  
3          Westway Inn Motel, Neepawa  
4  Holiday Inn Express & Suites Edson

In [85]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>City Name</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Weather Description</dt><dd>{City_Descr}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [88]:
# 11a. Add a marker layer for each city to the map.
#max_temp = itinerary_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
#heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
#             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
#fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))